Select * from customer

-- Q1: What is the total revenue generated by male vs female customers
Select gender,SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender

-- Q2: Which customers used a discount but still spent more than the average purchase amount
SELECT customer_id,purchase_amount FROM customer
WHERE discount_applied='Yes' and purchase_amount>= (select AVG(purchase_amount) from customer)

--Q3: What are the top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average review rating" FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
limit 5

--Q4: Compare the average purchase amount between standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2) FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

--Q5: Do subscribed customers spend more?Compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status,COUNT(customer_id) as Total_customers,ROUND(AVG(purchase_amount),2) as Average_spend,SUM(purchase_amount) as Total_revenue
FROM customer
WHERE subscription_status in ('Yes','No')
GROUP BY subscription_status
ORDER BY Average_spend,Total_revenue DESC;

--Q6: Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as PURCHASE_PERCENT
FROM customer
GROUP BY item_purchased
ORDER BY PURCHASE_PERCENT DESC
limit 5;

--Q7: Segment customers into New,Returning and Loyal based on their total no. of previous purchases and show the count of each segment.
-- SELECT customer_id,
-- CASE WHEN previous_purchase<=30 THEN "New" ELSE CASE WHEN previous_purchase<=60 THEN "Returning" ELSE "Loyal" END
-- FROM customer
-- GROUP BY customer_id

with customer_type as (
select customer_id,previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment,count(*) as "Number of customers"
from customer_type
group by customer_segment;

--Q8: What are the top 3 most purchased products within each category?
with item_counts as(
SELECT category,item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)DESC) as item_rank
from customer
GROUP BY category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

--Q9: Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_customers FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status

--Q10: What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) as total_revenue FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC